version: '2.3'
services:
  facedetect:
    container_name: facedetect-service
    build: 
      context: ./face_detect
      dockerfile: Dockerfile-gpu
    ports:
     - "7003:7000"
    volumes:
     - ./face_detect:/app
    runtime: nvidia
    
  facemotion:
    container_name: facemotion-service
    build: 
      context: ./face_emotion 
      dockerfile: Dockerfile-gpu
    ports:
     - "7004:7000"
    volumes:
     - ./face_emotion:/app
    runtime: nvidia
    
  facefeatures:
    container_name: facefeatures-service
    build: 
      context: ./face_features
      dockerfile: Dockerfile-gpu
    ports:
     - "7005:7000"
    volumes:
     - ./face_features:/app
    runtime: nvidia
    
  facerecognition:
    container_name: facerecognition-service
    build: 
      context: ./face_recognition
      dockerfile: Dockerfile-gpu
    ports:
     - "7006:7000"
    volumes:
     - ./face_recognition:/app
    runtime: nvidia
